openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'AWS Compute Optimizer #X Amz Target=ComputeOptimizerService.DeleteRecommendationPreferences #X Amz Target=ComputeOptimizerService.DeleteRecommendationPreferences #X Amz Target=ComputeOptimizerService.GetEffectiveRecommendationPreferences API'
  description: Compute Optimizer is a service that analyzes the configuration and utilization metrics of your Amazon Web Services compute resources, such as Amazon EC2 instances, Amazon EC2 Auto Scaling groups, Lambda functions, Amazon EBS volumes, and Amazon ECS services on Fargate. It reports whether your resources are optimal, and generates optimization recommendations to reduce the cost and improve the performance of your workloads. Compute Optimizer also provides recent utilization metric data, in addition to projected utilization metric data for the recommendations, which you can use to evaluate which recommendation provides the best price-performance trade-off. The analysis of your usage patterns can help you decide when to move or resize your running resources, and still meet your performance and capacity requirements. For more information about Compute Optimizer, including the required permissions to use the service, see the <a href="https://docs.aws.amazon.com/compute-optimizer/latest/ug/">Compute Optimizer User Guide</a>.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: compute-optimizer
  x-aws-signingName: compute-optimizer
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/compute-optimizer-2019-11-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://compute-optimizer.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Compute Optimizer multi-region endpoint
- url: https://compute-optimizer.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Compute Optimizer multi-region endpoint
- url: http://compute-optimizer.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Compute Optimizer endpoint for China (Beijing) and China (Ningxia)
- url: https://compute-optimizer.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Compute Optimizer endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=ComputeOptimizerService.GetEffectiveRecommendationPreferences'
paths:
  /#X-Amz-Target=ComputeOptimizerService.GetEffectiveRecommendationPreferences:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetEffectiveRecommendationPreferences
      description: <p>Returns the recommendation preferences that are in effect for a given resource, such as enhanced infrastructure metrics. Considers all applicable preferences that you might have set at the resource, account, and organization level.</p> <p>When you create a recommendation preference, you can set its status to <code>Active</code> or <code>Inactive</code>. Use this action to view the recommendation preferences that are in effect, or <code>Active</code>.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEffectiveRecommendationPreferencesResponse'
              examples:
                GetEffectiveRecommendationPreferences200Example:
                  summary: Default GetEffectiveRecommendationPreferences 200
                  x-microcks-default: true
                  value:
                    enhancedInfrastructureMetrics: example
                    externalMetricsPreference: example
        '480':
          description: OptInRequiredException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OptInRequiredException'
              examples:
                GetEffectiveRecommendationPreferences480Example:
                  summary: Default GetEffectiveRecommendationPreferences 480
                  x-microcks-default: true
                  value: example
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                GetEffectiveRecommendationPreferences481Example:
                  summary: Default GetEffectiveRecommendationPreferences 481
                  x-microcks-default: true
                  value: example
        '482':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                GetEffectiveRecommendationPreferences482Example:
                  summary: Default GetEffectiveRecommendationPreferences 482
                  x-microcks-default: true
                  value: example
        '483':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                GetEffectiveRecommendationPreferences483Example:
                  summary: Default GetEffectiveRecommendationPreferences 483
                  x-microcks-default: true
                  value: example
        '484':
          description: InvalidParameterValueException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterValueException'
              examples:
                GetEffectiveRecommendationPreferences484Example:
                  summary: Default GetEffectiveRecommendationPreferences 484
                  x-microcks-default: true
                  value: example
        '485':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                GetEffectiveRecommendationPreferences485Example:
                  summary: Default GetEffectiveRecommendationPreferences 485
                  x-microcks-default: true
                  value: example
        '486':
          description: MissingAuthenticationToken
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissingAuthenticationToken'
              examples:
                GetEffectiveRecommendationPreferences486Example:
                  summary: Default GetEffectiveRecommendationPreferences 486
                  x-microcks-default: true
                  value: example
        '487':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                GetEffectiveRecommendationPreferences487Example:
                  summary: Default GetEffectiveRecommendationPreferences 487
                  x-microcks-default: true
                  value: example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetEffectiveRecommendationPreferencesRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - ComputeOptimizerService.GetEffectiveRecommendationPreferences
      summary: Amazon Compute Optimizer Get Effective Recommendation Preferences
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=ComputeOptimizerService.GetEffectiveRecommendationPreferences'
components:
  schemas:
    ExternalMetricsPreference:
      type: object
      properties:
        source:
          allOf:
          - $ref: '#/components/schemas/ExternalMetricsSource'
          - description: ' Contains the source options for external metrics preferences. '
      description: ' Describes the external metrics preferences for EC2 rightsizing recommendations. '
    InternalServerException: {}
    ThrottlingException: {}
    ServiceUnavailableException: {}
    MissingAuthenticationToken: {}
    OptInRequiredException: {}
    GetEffectiveRecommendationPreferencesResponse:
      type: object
      properties:
        enhancedInfrastructureMetrics:
          allOf:
          - $ref: '#/components/schemas/EnhancedInfrastructureMetrics'
          - description: <p>The status of the enhanced infrastructure metrics recommendation preference. Considers all applicable preferences that you might have set at the resource, account, and organization level.</p> <p>A status of <code>Active</code> confirms that the preference is applied in the latest recommendation refresh, and a status of <code>Inactive</code> confirms that it's not yet applied to recommendations.</p> <p>To validate whether the preference is applied to your last generated set of recommendations, review the <code>effectiveRecommendationPreferences</code> value in the response of the <a>GetAutoScalingGroupRecommendations</a> and <a>GetEC2InstanceRecommendations</a> actions.</p> <p>For more information, see <a href="https://docs.aws.amazon.com/compute-optimizer/latest/ug/enhanced-infrastructure-metrics.html">Enhanced infrastructure metrics</a> in the <i>Compute Optimizer User Guide</i>.</p>
        externalMetricsPreference:
          allOf:
          - $ref: '#/components/schemas/ExternalMetricsPreference'
          - description: <p>The provider of the external metrics recommendation preference. Considers all applicable preferences that you might have set at the account and organization level.</p> <p>If the preference is applied in the latest recommendation refresh, an object with a valid <code>source</code> value appears in the response. If the preference isn't applied to the recommendations already, then this object doesn't appear in the response.</p> <p>To validate whether the preference is applied to your last generated set of recommendations, review the <code>effectiveRecommendationPreferences</code> value in the response of the <a>GetEC2InstanceRecommendations</a> actions.</p> <p>For more information, see <a href="https://docs.aws.amazon.com/compute-optimizer/latest/ug/external-metrics-ingestion.html">Enhanced infrastructure metrics</a> in the <i>Compute Optimizer User Guide</i>.</p>
    InvalidParameterValueException: {}
    GetEffectiveRecommendationPreferencesRequest:
      type: object
      required:
      - resourceArn
      title: GetEffectiveRecommendationPreferencesRequest
      properties:
        resourceArn:
          allOf:
          - $ref: '#/components/schemas/ResourceArn'
          - description: The Amazon Resource Name (ARN) of the resource for which to confirm effective recommendation preferences. Only EC2 instance and Auto Scaling group ARNs are currently supported.
    ResourceNotFoundException: {}
    AccessDeniedException: {}
    ResourceArn:
      type: string
    ExternalMetricsSource:
      type: string
      enum:
      - Datadog
      - Dynatrace
      - NewRelic
      - Instana
    EnhancedInfrastructureMetrics:
      type: string
      enum:
      - Active
      - Inactive
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/compute-optimizer/
x-hasEquivalentPaths: true
