openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: 'AWS Compute Optimizer #X Amz Target=ComputeOptimizerService.DeleteRecommendationPreferences #X Amz Target=ComputeOptimizerService.DeleteRecommendationPreferences #X Amz Target=ComputeOptimizerService.GetEnrollmentStatusesForOrganization #X Amz Target=ComputeOptimizerService.GetEnrollmentStatusesForOrganization #X Amz Target=ComputeOptimizerService.GetEnrollmentStatusesForOrganization API'
  description: Compute Optimizer is a service that analyzes the configuration and utilization metrics of your Amazon Web Services compute resources, such as Amazon EC2 instances, Amazon EC2 Auto Scaling groups, Lambda functions, Amazon EBS volumes, and Amazon ECS services on Fargate. It reports whether your resources are optimal, and generates optimization recommendations to reduce the cost and improve the performance of your workloads. Compute Optimizer also provides recent utilization metric data, in addition to projected utilization metric data for the recommendations, which you can use to evaluate which recommendation provides the best price-performance trade-off. The analysis of your usage patterns can help you decide when to move or resize your running resources, and still meet your performance and capacity requirements. For more information about Compute Optimizer, including the required permissions to use the service, see the <a href="https://docs.aws.amazon.com/compute-optimizer/latest/ug/">Compute Optimizer User Guide</a>.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: compute-optimizer
  x-aws-signingName: compute-optimizer
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/compute-optimizer-2019-11-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://compute-optimizer.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Compute Optimizer multi-region endpoint
- url: https://compute-optimizer.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Compute Optimizer multi-region endpoint
- url: http://compute-optimizer.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Compute Optimizer endpoint for China (Beijing) and China (Ningxia)
- url: https://compute-optimizer.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Compute Optimizer endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=ComputeOptimizerService.GetEnrollmentStatusesForOrganization'
paths:
  /#X-Amz-Target=ComputeOptimizerService.GetEnrollmentStatusesForOrganization:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetEnrollmentStatusesForOrganization
      description: <p>Returns the Compute Optimizer enrollment (opt-in) status of organization member accounts, if your account is an organization management account.</p> <p>To get the enrollment status of standalone accounts, use the <a>GetEnrollmentStatus</a> action.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEnrollmentStatusesForOrganizationResponse'
              examples:
                GetEnrollmentStatusesForOrganization200Example:
                  summary: Default GetEnrollmentStatusesForOrganization 200
                  x-microcks-default: true
                  value:
                    accountEnrollmentStatuses: example
                    nextToken: example
        '480':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                GetEnrollmentStatusesForOrganization480Example:
                  summary: Default GetEnrollmentStatusesForOrganization 480
                  x-microcks-default: true
                  value: example
        '481':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                GetEnrollmentStatusesForOrganization481Example:
                  summary: Default GetEnrollmentStatusesForOrganization 481
                  x-microcks-default: true
                  value: example
        '482':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                GetEnrollmentStatusesForOrganization482Example:
                  summary: Default GetEnrollmentStatusesForOrganization 482
                  x-microcks-default: true
                  value: example
        '483':
          description: InvalidParameterValueException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterValueException'
              examples:
                GetEnrollmentStatusesForOrganization483Example:
                  summary: Default GetEnrollmentStatusesForOrganization 483
                  x-microcks-default: true
                  value: example
        '484':
          description: MissingAuthenticationToken
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissingAuthenticationToken'
              examples:
                GetEnrollmentStatusesForOrganization484Example:
                  summary: Default GetEnrollmentStatusesForOrganization 484
                  x-microcks-default: true
                  value: example
        '485':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                GetEnrollmentStatusesForOrganization485Example:
                  summary: Default GetEnrollmentStatusesForOrganization 485
                  x-microcks-default: true
                  value: example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetEnrollmentStatusesForOrganizationRequest'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - ComputeOptimizerService.GetEnrollmentStatusesForOrganization
      summary: Amazon Compute Optimizer Get Enrollment Statuses for Organization
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=ComputeOptimizerService.GetEnrollmentStatusesForOrganization'
components:
  parameters:
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  schemas:
    GetEnrollmentStatusesForOrganizationRequest:
      type: object
      title: GetEnrollmentStatusesForOrganizationRequest
      properties:
        filters:
          allOf:
          - $ref: '#/components/schemas/EnrollmentFilters'
          - description: An array of objects to specify a filter that returns a more specific list of account enrollment statuses.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: The token to advance to the next page of account enrollment statuses.
        maxResults:
          allOf:
          - $ref: '#/components/schemas/MaxResults'
          - description: <p>The maximum number of account enrollment statuses to return with a single request. You can specify up to 100 statuses to return with each request.</p> <p>To retrieve the remaining results, make another request with the returned <code>nextToken</code> value.</p>
    MaxResults:
      type: integer
      minimum: 0
      maximum: 1000
    NextToken:
      type: string
    StatusReason:
      type: string
    ServiceUnavailableException: {}
    InternalServerException: {}
    InvalidParameterValueException: {}
    MissingAuthenticationToken: {}
    EnrollmentFilter:
      type: object
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/EnrollmentFilterName'
          - description: <p>The name of the filter.</p> <p>Specify <code>Status</code> to return accounts with a specific enrollment status (for example, <code>Active</code>).</p>
        values:
          allOf:
          - $ref: '#/components/schemas/FilterValues'
          - description: <p>The value of the filter.</p> <p>The valid values are <code>Active</code>, <code>Inactive</code>, <code>Pending</code>, and <code>Failed</code>.</p>
      description: Describes a filter that returns a more specific list of account enrollment statuses. Use this filter with the <a>GetEnrollmentStatusesForOrganization</a> action.
    AccessDeniedException: {}
    LastUpdatedTimestamp:
      type: string
      format: date-time
    EnrollmentFilters:
      type: array
      items:
        $ref: '#/components/schemas/EnrollmentFilter'
    ThrottlingException: {}
    Status:
      type: string
      enum:
      - Active
      - Inactive
      - Pending
      - Failed
    GetEnrollmentStatusesForOrganizationResponse:
      type: object
      properties:
        accountEnrollmentStatuses:
          allOf:
          - $ref: '#/components/schemas/AccountEnrollmentStatuses'
          - description: An array of objects that describe the enrollment statuses of organization member accounts.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: <p>The token to use to advance to the next page of account enrollment statuses.</p> <p>This value is null when there are no more pages of account enrollment statuses to return.</p>
    EnrollmentFilterName:
      type: string
      enum:
      - Status
    AccountEnrollmentStatus:
      type: object
      properties:
        accountId:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: The Amazon Web Services account ID.
        status:
          allOf:
          - $ref: '#/components/schemas/Status'
          - description: The account enrollment status.
        statusReason:
          allOf:
          - $ref: '#/components/schemas/StatusReason'
          - description: <p>The reason for the account enrollment status.</p> <p>For example, an account might show a status of <code>Pending</code> because member accounts of an organization require more time to be enrolled in the service.</p>
        lastUpdatedTimestamp:
          allOf:
          - $ref: '#/components/schemas/LastUpdatedTimestamp'
          - description: The Unix epoch timestamp, in seconds, of when the account enrollment status was last updated.
      description: Describes the enrollment status of an organization's member accounts in Compute Optimizer.
    AccountEnrollmentStatuses:
      type: array
      items:
        $ref: '#/components/schemas/AccountEnrollmentStatus'
    FilterValue:
      type: string
    FilterValues:
      type: array
      items:
        $ref: '#/components/schemas/FilterValue'
    AccountId:
      type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/compute-optimizer/
x-hasEquivalentPaths: true
